### ISSUE TITLE
Allow deletion of tweets given a status id

### ISSUE THREAD

**Issue by kevinklaes** [Resisty/HorseFinder#4]
Authenticate if you want, but provide some way for a user to moderate the tweets in the feed if an inappropriate one gets through.

**Comment by Resisty** [comment]
This is actually stupid hard, because unretweeting something is, for whatever reason, almost impossible. Finding the ID to delete requires the user to GET its timeline and search through the status updates for whatever you want to unretweet OR find the retweets for the original tweet, hope it has fewer than 100 retweets, search through those, and match HorseFinderBot to the user.
